source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RappleColorPicker_Example', :exclusive => true do
  pod "RappleColorPicker", :path => "../"
end

target 'RappleColorPicker_Tests', :exclusive => true do
  pod "RappleColorPicker", :path => "../"

  
end
